### ISSUE TITLE
Make ansible host tor installation optional

### ISSUE THREAD

**Issue by xmatthias** [nusenu/ansible-relayor#148]
Would a PR be accepted to make the "offline master key" management or is this completely against the purpose of this role / mindset of the author?

one benefit of this would be that the local dependencies for this role would be dropped

I understand that security of the master keys is important, but the tor project calls offline master keys an "advanced security feature" in their new [relay guide](https://trac.torproject.org/projects/tor/wiki/TorRelayGuide) - so in my understanding it would also be fine to run relays with master keys on the (secured / hardened) Relay server.

**Comment by nusenu** [comment]
Hello Matthias,

thanks for your input.

I didn't think that having tor as a dependency (just the binary no need for a daemon)
is not a big requirement since it is shipped by almost all distributions.

Could you elaborate why that dependency is a problem for you or why you would like to
avoid that dependency?

Matthias:
> I understand that security of the master keys is important, but the
> tor project calls offline master keys an "advanced security feature"

Sorry I didn't mean to scare people away from that
feature by using "advanced" in that sentence - quite the opposite. 
I updated that part in the guide and replaced advanced with strong.

> so in my understanding it would also be fine to run relays with
> master keys on the (secured / hardened) Relay server.

Yes, it is totally fine to run Tor relays without using OfflineMasterKeys
(most of the Tor network does not use that feature I guess).

**Comment by xmatthias** [comment]
It's not so much the tor dependency that bothers me - but having the keys on the laptop (which people bring with themselfs (across borders and such) - and i would therefore consider less secure than a hardened server - but i guess that depends on the country the server resides in).
It would make the role more portable - and would elliminate the need to run this every X days - i guess that's the main point that bothers me.

By not having the keys on the laptop, the local tor dependency would automatically go away - it's a side-effect, not the main point. 

Strong sounds better than advanced (which makes it sound more complicated than it really is).

**Comment by nusenu** [comment]
Thanks for clarifying your concerns and motivation for this ticket. 

Matthias:
> It's not so much the tor dependency that bothers me - but having the 
> keys on the laptop (which people bring with themselfs (across
> borders and such) - and i would therefore consider less secure than
> a hardened server
in the introduction to this role [1] I wrote:
> When choosing your ansible control machine be aware that it stores
> all your relay keys, so choose the safest machine you have.

That said, in your scenario the server sounds like it is the safest option,
meaning your server should be your control machine to avoid having all 
the keys on the laptop.

This might sound counterintuitive at first since in that case your "offline" keys
would be located on an online server but that is still a lot safer than
no OfflineMasterKey mode at all because the tor daemon(s) do not get access to the 
master keys (at least at a user level - assuming proper permissions).

> and would elliminate the need
> to run this every X days - i guess that's the main point that bothers
> me.

As for the reoccurring requirement to renew keys: 
You can configure the lifetime using tor_signingkeylifetime_days,
so if one month (default value) is not suitable for you, you can also set it to
a much longer lifetime (longer = bigger impact in case of a security breach).


Does that answer your concerns?




[1] https://medium.com/@nusenu/deploying-tor-relays-with-ansible-6612593fa34d

**Comment by xmatthias** [comment]
so you'd run ansible on the remote server against localhost ... that may work, yes.

I think, this discussion moves in another way than i intendet it do.
My plan was to implement the above - but i wanted to ask if that is against the idea of role (pushing people to use offline keys). I understood that it would be - so i'm going to drop that idea.

Thanks for clarifying :)
