### ISSUE TITLE
add kitchen test case with public IPs

### ISSUE THREAD

**Issue by nusenu** [nusenu/ansible-relayor#154]
Currently we use default (=private) IP configuration for test-VMs which means that the parts which depend on public IPs do not get any testing.

Lets add a new test case:
* t-guard-2publicIPs

The only difference to the current t-guard is, that the VM has two public IPs and `tor_maxPublicIPs` is set to 2

**Comment by Lirt** [comment]
This can be a little tricky. 

To make provisioning happen, ansible must connect to tested machine via SSH. That means there must be one locally reachable IP address. 

If we assign public IP address to VM, it won't be reachable from ansible, since ansible will be connecting to Internet according to local routing table and default gateway.

We can however assign one private address and two public addresses and setup playbook in a way it will setup tor on network interfaces with public addresses.

There is also one question, will these public addresses be assigned both to one network interface (NI), or one to first NI and second address to second NI?

Configuration of NIs can then be applied using [driver parameters](https://github.com/test-kitchen/kitchen-vagrant#-network) or using custom script/commands in vagrant provisioning file (vagrantfiles).

So far configuration using [public_network](https://www.vagrantup.com/docs/networking/public_network.html#default-network-interface) is not running well, because I need to specify over which interface will it be bridged. 

I think that we only need to simulate public interfaces (they do not need to be actually reachable), so custom script may work better.

**Comment by nusenu** [comment]
The idea was to just add two more IPs in addition to what is already there currently (and which is used to connect to the VM) so we should not have any troubles connecting to the VM with the usual means.

These IPs can be aliases for the interface that is already there, we do not need an additional network interface - if that makes things easier.

The role itself will take care of using the public IP addresses only out of the box.

Thanks for grabbing this issue.

**Comment by nusenu** [comment]
I noticed that my email reply to this issue didn't end up here.

I wrote:
thanks for the patch!

I'll do some reading to make sure there is no 'vagrant-way' to create the same network interfaces/ip
addressing

**Comment by nusenu** [comment]
the branch above works on all platforms but fails on CentOS 7, 
because we are no longer able to reach the VM via SSH (timeout)

**Comment by Lirt** [comment]
Same to me. CentOS7 is unable to SSH. Vagrant config looks like this and seems OK (like other Vagrantfiles).

```bash
cat .kitchen/kitchen-vagrant/t-guard-2publicIPs-centos-7/Vagrantfile

Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7"
  c.vm.hostname = "t-guard-2publicIPs-centos-7.vagrantup.com"
  c.vm.network(:private_network, {:type=>"dhcp"})
  c.vm.network(:private_network, {:ip=>"192.0.2.10/24"})
  c.vm.network(:private_network, {:ip=>"198.51.100.10/24"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/home/<USERNAME>/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "512"]
  end
```

**Comment by nusenu** [comment]
Thank you for confirming!
upstream bugreport:
https://github.com/chef/bento/issues/1023

**Comment by Lirt** [comment]
Btw. I didn't know that you can override `driver.network` in kitchen suite. That's why I tried to configure it using ansible. It looks good now.

**Comment by nusenu** [comment]
the above commit should fix the previous issues (even though still very slow).

Testing is appreciated.

**Comment by nusenu** [comment]
Also works with OpenBSD, merged.
