### ISSUE TITLE
Add a way to avoid sudo if the user is already root

### ISSUE THREAD

**Issue by CristianCantoro** [nusenu/ansible-relayor#49]
On DigitalOcean and other ISP  the machines come with only the `root` user present. By default (on Debian 8.0 and 8.1) `sudo` is not installed.

If the machine is dedicated to be a Tor node I see no reason to install `sudo` and add another user for the installation of Tor.

It should be possible then to check if the user is already `root` and, if so, do not add `sudo` to all commands. Furthermore the `sudo` directive in anslble playbooks is [deprecated](https://docs.ansible.com/ansible/become.html).

If setting up the node with `root` is not advisable then it should be mentioned (e.g. in the README).

**Comment by CristianCantoro** [comment]
Pull requesst https://github.com/nusenu/ansible-relayor/pull/50 solves this.

**Comment by nusenu** [comment]
> On DigitalOcean and other ISP  the machines come with only the `root`
> user present.

Yes, that is pretty standard and many hoster will deploy your pubkey
for root on every new VM.
Setting up python, a user, sshkey and sudo is not a big effort if you do
it via automated means.

https://docs.ansible.com/ansible/user_module.html
https://docs.ansible.com/ansible/authorized_key_module.html


To make it easy for people to disable RemoteRootLogin we could create a
playbook to actually setup these requirements as well (separate role).

> If the machine is dedicated to be a Tor node I see no reason to
> install `sudo` and add another user fot installing Tor.

Even though that is outside the scope of this role, I'd encourage
everyone to run sshd with PermitRootLogin set to 'no'.

If you run the entire role as root on the target you loose the ability
to do fine grained privilege separation on a per task basis. Currently
that is no big deal since most things need root anyway.

> It should be
> possible then to check if the user is already `root` and, if so, do
> not add `sudo` to all commands. If this setup is deprecated then it
> should be specified (e.g. in the README):

I'll try to clarify that in the README.


Thanks for pointing out that sudo is deprecated.
